/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tema1.h"

bool_t
xdr_response_code (XDR *xdrs, response_code *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_auth_response (XDR *xdrs, auth_response *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token, ~0))
		 return FALSE;
	 if (!xdr_response_code (xdrs, &objp->code))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_access_response (XDR *xdrs, access_response *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->availability))
		 return FALSE;
	 if (!xdr_response_code (xdrs, &objp->code))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_access_params (XDR *xdrs, access_params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->refresh))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_refresh_params (XDR *xdrs, refresh_params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->refresh))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_valid_action_params (XDR *xdrs, valid_action_params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->op, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resource, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	return TRUE;
}
